import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: `Terms of Service · ${SITE.name}`,
  description: `Terms of Service for ${SITE.name}.`,
};

export default function TermsOfService() {
  return (
    <div className="flex min-h-[100svh] flex-col bg-white text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100">
      <main className="mx-auto w-full max-w-2xl flex-1 px-4 py-8">
        <Link href="/" className="text-sm text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100">
          ← Back to chat
        </Link>
        <h1 className="mt-4 text-2xl font-semibold">Terms of Service</h1>
        <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
          Effective {SITE.legalEffectiveDate}
        </p>

        <Section title="1. The service">
          <p>
            {SITE.name} is an AI chat application accessible at {linkText(SITE.productionUrl)}{" "}
            and inside the MiniPay wallet. Each answer is generated by a third-party large language
            model (currently Groq Llama 3.3 70B with Cerebras gpt-oss-120b as a fallback) and is
            delivered after a payment of {SITE.pricePerQuery} {SITE.paymentToken} on{" "}
            {SITE.network} settled via the x402 protocol.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be at least 13 years old and legally able to enter into a contract in your
            jurisdiction. By using {SITE.name} you confirm you meet these requirements and that
            you are not located in a country or on a list of persons restricted from receiving
            blockchain or AI services under the laws applicable to you.
          </p>
        </Section>

        <Section title="3. Pricing and payments">
          <p>
            The current price per answer is {SITE.pricePerQuery} payable in {SITE.paymentToken} on{" "}
            {SITE.network}. The price may change without prior notice; the price you sign for in
            your wallet at the moment of each query is the final price for that query. All payments
            are settled on-chain and are non-refundable once the answer is generated, including
            cases where you are unsatisfied with the response. If the AI provider is unreachable
            we return an error before settling, so failed providers should not result in a charge.
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to use {SITE.name} to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>generate or distribute illegal content;</li>
            <li>infringe intellectual-property rights of third parties;</li>
            <li>create content intended to harass, defame, or harm others;</li>
            <li>attempt to extract personal data about the operator or other users;</li>
            <li>circumvent the payment flow or attack the underlying infrastructure.</li>
          </ul>
          <p className="mt-3">
            We may block addresses that abuse the service. Funds already paid for delivered answers
            will not be returned.
          </p>
        </Section>

        <Section title="5. AI-generated content">
          <p>
            Answers are produced by third-party machine-learning models and may be inaccurate,
            incomplete, biased, or out of date. {SITE.name} does not guarantee the correctness or
            suitability of any answer for any purpose. You are solely responsible for reviewing
            answers before relying on them — in particular, do not use {SITE.name} as a substitute
            for professional medical, legal, financial, or safety advice.
          </p>
        </Section>

        <Section title="6. On-chain receipts">
          <p>
            Every paid query causes our smart contract at{" "}
            {linkText(SITE.contractAddress, SITE.contractExplorerUrl)} to emit a public{" "}
            <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs dark:bg-zinc-900">
              PromptPaid
            </code>{" "}
            event with your wallet address, the model used, a keccak256 hash of your prompt, and a
            timestamp. By using {SITE.name} you acknowledge that this metadata becomes public and
            permanent on-chain. The raw text of your prompt is{" "}
            <strong>not</strong> stored on-chain.
          </p>
        </Section>

        <Section title="7. No warranties">
          <p>
            {SITE.name} is provided “as is” and “as available” without warranties of any kind,
            whether express or implied. We disclaim all warranties of merchantability, fitness for
            a particular purpose, and non-infringement to the maximum extent permitted by law.
          </p>
        </Section>

        <Section title="8. Limitation of liability">
          <p>
            To the maximum extent permitted by law, {SITE.name} and its operator are not liable
            for any indirect, incidental, special, consequential, or punitive damages arising from
            your use of the service. Our total liability for any claim arising out of these terms
            is limited to the amount you paid {SITE.name} in the 30 days preceding the event that
            gave rise to the claim.
          </p>
        </Section>

        <Section title="9. Changes">
          <p>
            We may update these terms at any time by changing this page. Continued use of{" "}
            {SITE.name} after a change constitutes acceptance of the updated terms.
          </p>
        </Section>

        <Section title="10. Contact">
          <p>
            For questions, support requests, or legal notices, reach us on Telegram at{" "}
            {linkText(SITE.supportLabel, SITE.supportUrl)}.
          </p>
        </Section>
      </main>
      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-6">
      <h2 className="text-base font-semibold">{title}</h2>
      <div className="mt-2 space-y-2 text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
        {children}
      </div>
    </section>
  );
}

function linkText(text: string, href?: string) {
  return (
    <a
      href={href ?? text}
      target="_blank"
      rel="noopener noreferrer"
      className="text-zinc-900 underline underline-offset-2 dark:text-zinc-100"
    >
      {text}
    </a>
  );
}
